sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 162113
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tFdZfrnmznDG6Q2B5My
    access-key-secret: ypBGUc34zFmB1MEFDZfwTRS4j9lJQo
    bucket-name: big-event-wcdy
